default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: 5432
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: municipe_development

test:
  <<: *default
  database: municipe_test

production:
  <<: *default
  database: municipe_production
  username: municipe
  password: <%= ENV["MUNICIPE_DATABASE_PASSWORD"] %>